[package]
name = "leitsys_web"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23.1"
dioxus = { version = "0.7.1", features = ["router", "web"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", features = ["web"], version = "0.0.1", default-features = false }
dioxus-sdk-time = "0.7.0"
reqwest = { version = "0.13.5", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
time = { version = "0.3", features = ["macros", "wasm-bindgen"] }
tracing = "0.1"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
